[tool.poetry]
name = "simplebot"
version = "0.1.0"
description = ""
authors = ["Erik Anderson <erik.kristofer.anderson@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
discord-py-interactions = "^5.9.2"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
